/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni_202557201040;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ThinkPad
 */
public class FrameDashboard extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameDashboard.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form FrameDashboard
     */
    public FrameDashboard() {
        initComponents();
        inisiasiPanel();
    }

    void inisiasiPanel() {
        cardLayout = (CardLayout)PanelContent.getLayout();
        PanelContent.add(new panelDashboard(), "dashboard");
        PanelContent.add(new panelJurusan(), "jurusan");
        PanelContent.add(new panelGuru(), "guru");
        PanelContent.add(new panelKelas(), "kelas");
        PanelContent.add(new panelSiswa(), "siswa");
        PanelContent.add(new panelAbout(), "about");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bDashboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Alumni");
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        PanelSidebar.setBackground(new java.awt.Color(0, 153, 255));
        PanelSidebar.setMinimumSize(new java.awt.Dimension(200, 10));
        PanelSidebar.setPreferredSize(new java.awt.Dimension(250, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-graduation-60.png"))); // NOI18N
        jLabel1.setText("Aloomni");
        jLabel1.setIconTextGap(10);

        bDashboard.setBackground(new java.awt.Color(0, 153, 255));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-dashboard-20.png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.setIconTextGap(10);
        bDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDashboardActionPerformed(evt);
            }
        });

        bJurusan.setBackground(new java.awt.Color(0, 153, 255));
        bJurusan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-department-20.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.setIconTextGap(10);
        bJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJurusanActionPerformed(evt);
            }
        });

        bGuru.setBackground(new java.awt.Color(0, 153, 255));
        bGuru.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-teacher-20.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.setIconTextGap(10);
        bGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuruActionPerformed(evt);
            }
        });

        bKelas.setBackground(new java.awt.Color(0, 153, 255));
        bKelas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-class-20.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.setIconTextGap(10);
        bKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKelasActionPerformed(evt);
            }
        });

        bSiswa.setBackground(new java.awt.Color(0, 153, 255));
        bSiswa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-user-20.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.setIconTextGap(10);
        bSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiswaActionPerformed(evt);
            }
        });

        bAbout.setBackground(new java.awt.Color(0, 153, 255));
        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-about-20.png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.setIconTextGap(10);
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });

        bLogout.setBackground(new java.awt.Color(0, 153, 255));
        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201040/img/icons8-logout-20.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.setIconTextGap(10);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSidebarLayout = new javax.swing.GroupLayout(PanelSidebar);
        PanelSidebar.setLayout(PanelSidebarLayout);
        PanelSidebarLayout.setHorizontalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(bDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bJurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bGuru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSidebarLayout.setVerticalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(bDashboard)
                .addGap(0, 0, 0)
                .addComponent(bJurusan)
                .addGap(0, 0, 0)
                .addComponent(bGuru)
                .addGap(0, 0, 0)
                .addComponent(bKelas)
                .addGap(0, 0, 0)
                .addComponent(bSiswa)
                .addGap(0, 0, 0)
                .addComponent(bAbout)
                .addGap(0, 0, 0)
                .addComponent(bLogout)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSidebar, java.awt.BorderLayout.LINE_START);

        PanelContent.setBackground(new java.awt.Color(255, 255, 255));
        PanelContent.setPreferredSize(new java.awt.Dimension(250, 480));
        PanelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah anda yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        switch (pilihan) {
            case JOptionPane.YES_OPTION:
                dispose();
                new FrameLogin().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.put("Button.borderWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel PanelSidebar;
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
