/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202557201040;

/**
 *
 * @author ThinkPad
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 477));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel6.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jumlah Jurusan");
        jLabel2.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JJ");
        jLabel1.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(124, 100));
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3);

        jPanel4.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Guru");
        jLabel3.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel7.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JG");
        jLabel4.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(124, 100));
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4);

        jPanel5.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 477));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kelas");
        jLabel5.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel8.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JK");
        jLabel6.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel6.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(124, 100));
        jPanel8.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel5);

        jPanel9.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 477));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel10.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah Siswa");
        jLabel7.setMaximumSize(new java.awt.Dimension(46, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(46, 30));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(46, 30));
        jPanel10.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("JS");
        jLabel8.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel8.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(124, 100));
        jPanel10.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel9);

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
